### ISSUE TITLE
Lack of a license

### ISSUE THREAD

**Issue by ducalpha** [strobi/cookie-notice-scanner#1]
Could you please add a license to the project that allow others to reuse your work? 

The project is very useful for our work but I have no right to use it because "without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work." [[Github guidelines](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license)]

**Comment by strobi** [comment]
The project is now available under the MIT license.
